### ISSUE TITLE
Implement support for zero nested key

### ISSUE THREAD

**Issue by rainerborene** [fiverr/i18n.js#52]
Hi,

Just found out that this library does not support the nested `zero` key, like:

```yaml
zero: 'no messages',
one: 'one message',
other: '%{count} messages'
``` 

I can work on this feature. would you merge if I come up with a patch?
